apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-test24-infra
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:ts-idp-poc/test24-infra.git
        revision: main
        directories:
            - path: yaml
        interval: 1m
  template:
    metadata:
      name: 'test24-infra'
    spec:
      project: test24
      source:
        repoURL: git@github.com:ts-idp-poc/test24-infra.git
        targetRevision: main
        path: yaml
        directory:
            recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "test24"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true