apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test47
    namespace: argocd
spec:
    description: test47 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test47"
    sourceRepos:
    - git@github.com:ts-idp-poc/test47-app.git
    - git@github.com:ts-idp-poc/test47-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test47