apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test19
    namespace: argocd
spec:
    description: test19 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test19"
    sourceRepos:
    - git@github.com:ts-idp-poc/test19-app.git
    - git@github.com:ts-idp-poc/test19-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test19