apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test20
    namespace: argocd
spec:
    description: test20 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test20"
    sourceRepos:
    - git@github.com:ts-idp-poc/test20-app.git
    - git@github.com:ts-idp-poc/test20-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test20