apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test38
    namespace: argocd
spec:
    description: test38 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test38"
    sourceRepos:
    - git@github.com:ts-idp-poc/test38-app.git
    - git@github.com:ts-idp-poc/test38-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test38