apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test54
    namespace: argocd
spec:
    description: test54 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test54"
    sourceRepos:
    - git@github.com:ts-idp-poc/test54-app.git
    - git@github.com:ts-idp-poc/test54-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test54