apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test21
    namespace: argocd
spec:
    description: test21 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test21"
    sourceRepos:
    - git@github.com:ts-idp-poc/test21-app.git
    - git@github.com:ts-idp-poc/test21-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test21