apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test52
    namespace: argocd
spec:
    description: test52 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test52"
    sourceRepos:
    - git@github.com:ts-idp-poc/test52-app.git
    - git@github.com:ts-idp-poc/test52-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test52