apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test55
    namespace: argocd
spec:
    description: test55 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test55"
    sourceRepos:
    - git@github.com:ts-idp-poc/test55-app.git
    - git@github.com:ts-idp-poc/test55-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test55