apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test23
    namespace: argocd
spec:
    description: test23 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test23"
    sourceRepos:
    - git@github.com:ts-idp-poc/test23-app.git
    - git@github.com:ts-idp-poc/test23-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test23