apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test53
    namespace: argocd
spec:
    description: test53 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test53"
    sourceRepos:
    - git@github.com:ts-idp-poc/test53-app.git
    - git@github.com:ts-idp-poc/test53-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test53