apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test51
    namespace: argocd
spec:
    description: test51 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test51"
    sourceRepos:
    - git@github.com:ts-idp-poc/test51-app.git
    - git@github.com:ts-idp-poc/test51-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test51